apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: hopeful-api
    newName: ghcr.io/quiescenttrip/gitops-test/hopeful-api
    newTag: c6926e2
